### ISSUE TITLE
XDeviceMonitor.exe crashes when connecting the second controller

### ISSUE THREAD

**Issue by sophialiuli** [Ximmerse/SDK#1]
Hi,

I received the outside-in dev kit from China, with special firmware for both PC and mobile. Tried it today, it works well, however when connecting the second controller in XDeviceMonitor.exe, the program crashes.

Is this a known issue? Any fix or update?

Thanks!

Sophia from EON Reality, Irvine CA USA.

Details:
Auto-connect feature seems not working, it didn't connect when enabled.

Manually connect works for the first controller. I can choose to connect either one of the two on the list (a pop up window).

After first controller is connected, if I try to connect the second controller, the program crashes immediately.

**Comment by yifu-ximmerse** [comment]
Hi, Sophia,
I am sorry you are having issues with our XDeviceMonitor.
I have heard some similar issues reported by other developers occasionally.
It is very hard for us reproduce this issue in house as we have found it only happens in certain environments(for example, if a developer has some kind of weird named BLE device around the PC, it will crash the XDeviceMonitor.)
For the time being, our solution is sharing the source code of the XDeviceMonitor, so developers can fix the issues only occurred in their dev environment. 
Here is the link to it :https://drive.google.com/open?id=0B81W2p2n4YO0eWt4ZFBjVWJrRzA <https://drive.google.com/open?id=0B81W2p2n4YO0eWt4ZFBjVWJrRzA>
It should work out of box, if you compile and run it with VS 2015.

Let us know if you have any other question.
Kind regards,
------------------
Yifu QIao 乔绎夫 |  SDK与应用
1 <>-805-501-2425


www.ximmerse.com <> | Twitter <https://twitter.com/Ximmerse> | Facebook <https://www.facebook.com/ximmersevr>

**Comment by sophialiuli** [comment]
Hi Yifu,

Thanks for the info. The source code you shared works on our side! Pleas consider replace the current XDeviceMonitor for the public on github.
