### ISSUE TITLE
Unity Failed to import package with error: Couldn't decompress package

### ISSUE THREAD

**Issue by theqwertman** [Ximmerse/SDK#1]
I'm unable to import the .unitypackage into Unity 5.3
I tried using an external unitypackage extractor, but it results in "missing prefab" errors.

**Comment by herohuyongtao** [comment]
What's your OS version, Win XP, 7, 8 or 10? Is your Unity x32 or x64? Better if you can provide some screenshots for the errors.

**Comment by theqwertman** [comment]
![2016-03-01_21h22_22](https://cloud.githubusercontent.com/assets/4174312/13451430/b7afc8b0-dff3-11e5-9899-892fa1214475.png)
Windows 10x64

**Comment by herohuyongtao** [comment]
Could you have a try on **Unity v5.1.3f1 (32-bit)**, on which our SDK is fully tested?

**Comment by theqwertman** [comment]
Is it possible that the contents of the unitypackage could be provided as a git repository, or zip file?

**Comment by herohuyongtao** [comment]
Please download the ZIP format of our latest SDK from [here](https://www.dropbox.com/s/49wgfrpdpsyx6li/Ximmerse%C2%A0SDK%C2%A02.0.zip?dl=0).
