### ISSUE TITLE
Unreal Engine 4 support ?

### ISSUE THREAD

**Issue by motorsep** [Ximmerse/SDK#3]
I work with Unreal Engine 4. Do you plan supporting it any time soon? Thanks.

**Comment by herohuyongtao** [comment]
@motorsep Our current SDK already supports Unreal Engine 4, please see the details in [our official Doc, Section: 8.2-5](http://ximmerse.github.io/SDK_Doc/#8.2-steps).

**Comment by motorsep** [comment]
After reading instructions, I see you ask devs to use Sixsense SDK. 

I was hoping for a straight forward drop in plugin where I don't need to hack around with the engine's code :/

Do you plan on providing pre-built plugin for UE4 so that devs can just use Blueprint and deploy to Gear VR without a need in building whole engine with yet another 3rd party SDK ?

Thanks.
