### ISSUE TITLE
Controller not detected in Unity

### ISSUE THREAD

**Issue by Cfirote** [Ximmerse/SDK#7]
Hi,

i have follow every step of the FAQ to pair the controller to theXdevice Monitor (who's working great now) but Unity didn't recognize it 

![image](https://cloud.githubusercontent.com/assets/28644515/26052514/0c79dbc0-3966-11e7-9f1b-8b11a6df5b82.png)

Can you help me ?

**Comment by yifu-ximmerse** [comment]
Hi, Cfirote,
3DoF pairing on Windows is different from 6DoF pairing. 
For 3Dof, you would need to pair the controller through "Manage Bluetooth Devices" window.
So, all you need to do is:

1. Shutdown XDeviceMonitor.
2. Pair controller in Manage Bluetooth Devices.
3. Run Unity.

![image](https://cloud.githubusercontent.com/assets/19679586/26072660/28e2eb4e-3961-11e7-9d82-b45352c13d7c.png)

**Comment by Cfirote** [comment]
Hi Yifu, thanks for your help.

That works now ^^
